### ISSUE TITLE
Feature request: Auto removal of old favorites?

### ISSUE THREAD

**Issue by Goles** [ztratar/followr#13]
I have accumulated around 10k favorites with my Account... we should make followr to remove old favorites 'pseduo randomly' too.

Just an idea.

**Comment by ztratar** [comment]
New version pushed to the chrome web store has this feature. :)

**Comment by gwintrob** [comment]
@ztratar I'm seeing the following error.  Any idea what's causing it?

![screenshot 2015-01-11 23 15 24](https://cloud.githubusercontent.com/assets/1240085/5699917/f6b9bfbe-99e7-11e4-81fc-1642498e285d.png)

**Comment by ztratar** [comment]
Woah I got that too. Fixed and pushing the chrome store now.
