### ISSUE TITLE
"blacklisted words" should also take the user name into account

### ISSUE THREAD

**Issue by Nowaker** [ztratar/followr#16]
Example: https://twitter.com/ArchUpdates/status/506942008053624832

I follow #archlinux tag, but I'd like to ignore @ArchUpdates user since all their tweets are automatic and there are so many of them, that followr rarely favorites #archlinux tagged tweets from other users.

I propose user names (e.g. ArchUpdates) and full names (e.g. ArchLinux Updates) are taken into account for blacklisted words.

**Comment by ztratar** [comment]
This feature is being added in 1.2.1, in chrome store in a couple hours.
