### ISSUE TITLE
Extension mysteriously providing Twitter .btn CSS styles

### ISSUE THREAD

**Issue by cobyism** [ztratar/followr#21]
With this extension loaded, any `.btn` button within the Twitter UI is getting the following user agent styles applied:

![2015-01-11 at 11 36 am](https://cloud.githubusercontent.com/assets/296432/5695080/301e8a62-9986-11e4-88b4-63f0296e54c8.png)

Resulting in really tight kerning everywhere, because of the `letter-spacing: 1px;` (most other styles are being overridden elsewhere in the actual CSS from twitter.com):

![2015-01-11 at 11 41 am](https://cloud.githubusercontent.com/assets/296432/5695086/039e9cce-9987-11e4-93ab-f11cec2335ba.png)
![2015-01-11 at 11 43 am](https://cloud.githubusercontent.com/assets/296432/5695088/0e69919a-9987-11e4-8181-6c0808660dc4.png)
![2015-01-11 at 11 43 am](https://cloud.githubusercontent.com/assets/296432/5695089/2794c9f0-9987-11e4-8b0f-4831878efd27.png)
![2015-01-11 at 11 44 am](https://cloud.githubusercontent.com/assets/296432/5695090/3afc6bc4-9987-11e4-93ee-6c7fb6c316e7.png)

If I disable *this* extension and don’t touch *anything else*, those styles go away. I’ve looked through the code of this extension though, and these styles don’t seem to be anywhere in this repo. **I have no idea** where this user agent stylesheet rule is coming from, but I’ve narrowed it down to *this extension being enabled* being the factor which reproduces the issue for me.

Notes:
- This style does not turn up when visiting non-twitter.com sites that have rules for `.btn`, for example if I view the Bootstrap docs it’s fine.
- I’ve installed the extension based in the current `master` branch, not via the Chrome extension store.

@ztratar Any ideas?

**Comment by ztratar** [comment]
The style is in general.css, directly under the .btn class. I'll change the letter spacing to auto and fix this!

**Comment by cobyism** [comment]
Weird, I could have sworn I grepped the whole repo for it. No idea why I didn’t find that. Thanks for the fix! :heart:
