### ISSUE TITLE
Twitter closes randomly

### ISSUE THREAD

**Issue by gwintrob** [ztratar/followr#22]
I find that when I'm scrolling through the feed or writing a tweet, the window will close automatically.  Seems to be a bug in the latest version of Followr.  Have you encountered this?

Thanks for all of your work @ztratar.

**Comment by ztratar** [comment]
Hey I actually found this was a bug on my end. Massive oops… haha. Fixed and pushing to chrome web store as we speak — should auto update on affected computers.

**Comment by ztratar** [comment]
Hey I actually found this was a bug on my end. Massive oops… haha. Fixed and pushing to chrome web store as we speak — should auto update on affected computers.


—
Zach TratarJobstart, Founder & CEO

ztratar@gmail.com - 630.854.8826

https://jobstart.co

**Comment by gwintrob** [comment]
@ztratar, thanks so much.  I owe you a beer big time.  Shoot me an email (gwintrob [at] gmail.com) if you're interested.
